spring:
  application:
    name: QUIZ-GATEWAY
  cloud:
    gateway:
      routes:
        - id: QUIZ-SERVICE
          uri: lb://QUIZ-SERVICE
          predicates:
            - Path=/quiz/**


        - id: QUESTION-SERVICE
          uri: lb://QUESTION-SERVICE
          predicates:
            - Path=/question/**

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
