spring:
  datasource:
    url: jdbc:mysql://localhost:3306/the_quiz_ms
    username: root
    password: root
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: QUIZ-SERVICE
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
